BASE_TASK_CONFIG_PATH: configs/tasks/rearrangpick_replica_cad.yaml

RL:
    REWARD_MEASURE: "rearrangepick_reward"
    SUCCESS_MEASURE: "rearrangepick_success"
    SUCCESS_REWARD: 2000.0
    SLACK_REWARD: -0.01

    DIST_REWARD: 20.0
    SUCC_REWARD: 10.0
    PICK_REWARD: 20.0
    CONSTRAINT_VIOLATE_PEN: 10.0
    DROP_PEN: 5.0
    WRONG_PICK_PEN: 5.0
    COLL_PEN: 1.0
    ROBO_OBJ_COLL_PEN: 0.0

    FORCE_PEN: 0.001
    MAX_FORCE_PEN: 1.0
    FORCE_END_PEN: 10.0

    USE_DIFF: True

    SUCC_THRESH: 0.15
    HOLD_THRESH: 0.09
    # In radians
    BASE_ANGLE_NOISE: 0.15
    BASE_NOISE: 0.05
    # If true, does not care about navigability or collisions with objects when spawning
    # robot
    EASY_INIT: False

MAX_COLLISIONS: 2000.0
FORCE_BASED: True
COUNT_OBJ_COLLISIONS: True
COUNT_ROBO_OBJ_COLLS: False
# A value of -1 means the episode will never terminate due to a force
# violation.
MAX_ACCUM_FORCE: 5000.0

ENV_NAME: "NavRLEnv"
