TENSORBOARD_DIR: "/checkpoint/eundersander/gala_kinematic/tb/gala_kinematic_ddppo"
CHECKPOINT_FOLDER: "/checkpoint/eundersander/gala_kinematic/ckpt/gala_kinematic_ddppo"
VIDEO_DIR: "../videos"
VIDEO_OPTION: ["disk"]
REWARD_SCALE: 1.0 # 0.01
NUM_CHECKPOINTS: 10
BATCHED_ENV: True
OVERLAP_PHYSICS: True
SAVE_VIDEOS_INTERVAL: 500
LOG_INTERVAL: 1
NUM_UPDATES: -1
TOTAL_NUM_STEPS: 50000000.0
NUM_ENVIRONMENTS: 2
MAX_EPISODE_LENGTH: 50
STAGGER: True
TEST_EPISODE_COUNT: 10
ENABLE_ROBOT_COLLISION: True
ENABLE_HELD_OBJECT_COLLISION: True
STATE_SENSORS:
  ROBOT_START_RELATIVE:
    TYPE: "RobotStartSensorConfig"
    polar: False
    obs_key: "robot_start_relative"
    shape: 3
  ROBOT_TARGET_RELATIVE:
    TYPE: "RobotTargetSensorConfig"
    polar: False
    obs_key: "robot_target_relative"
    shape: 3
  EE_START_RELATIVE:
    TYPE: "EEStartSensorConfig"
    polar: False
    obs_key: "ee_start_relative"
    shape: 3
  EE_TARGET_RELATIVE:
    TYPE: "EETargetSensorConfig"
    polar: False
    obs_key: "ee_target_relative"
    shape: 3
  ROBOT_EE_RELATIVE:
    TYPE: "RobotEESensorConfig"
    polar: False
    obs_key: "robot_ee_relative"
    shape: 3
  JOINT_SENSOR:
    TYPE: "RobotEESensorConfig"
    obs_key: "joint_pos"
    shape: 7
  STEP_COUNT_SENSOR:
    TYPE: "StepCountSensorConfig"
    obs_key: "step_count"
    shape: 3
VIDEO_RENDER_ALL_INFO: True
SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR", "ROBOT_START_RELATIVE", "ROBOT_TARGET_RELATIVE", "EE_START_RELATIVE", "EE_TARGET_RELATIVE", "ROBOT_EE_RELATIVE", "JOINT_SENSOR", "STEP_COUNT_SENSOR", "DEBUG_RGB_SENSOR"]
# SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR", "ROBOT_START_RELATIVE", "ROBOT_TARGET_RELATIVE", "EE_START_RELATIVE", "EE_TARGET_RELATIVE", "ROBOT_EE_RELATIVE", "JOINT_SENSOR", "STEP_COUNT_SENSOR"]
SIMULATOR:
  AGENTS: ['AGENT_0']
  AGENT_0:
    SENSORS: ['HEAD_RGB_SENSOR']
  HEAD_RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
WRITER_TYPE: "wb"
WB:
  PROJECT_NAME: "gala"
  ENTITY: "vincentpierre"
  GROUP: ""
  RUN_NAME: ""
RL:
  PPO:
    ppo_epoch: 1
    num_mini_batch: 2
    num_steps: 32
    entropy_coef: 0.0001
    lr: 2.5e-4
    use_normalized_advantage: True
    use_linear_lr_decay: False
    # max_grad_norm: 1.0e+32
  POLICY:
    name: "PointNavBaselinePolicy"
    action_distribution_type: "gaussian"
  DDPPO:
    backbone: "PointNavResNetPolicy"
FORCE_BLIND_POLICY: False
