BASE_TASK_CONFIG_PATH: configs/tasks/rearrange/reach_state.yaml

SENSE_PLAN_ACT:
  VERBOSE: True
  RUN_FREQ: 4
  KINEMATIC_CTRL: True
  N_GRASPS: 100
  MP_OBJ: True
  MP_MARGIN: null
  MP_RENDER: True
  TIMEOUT: 3
  EXEC_EE_THRESH: 0.1
  # "Priv" or "Reg"
  MP_SIM_TYPE: "Priv"
  VIDEO_DIR: 'data/vids'
  DEBUG_DIR: "data/mp_test"
  COUNT_OBJ_COLLISIONS: True
  GRASP_GEN_IS_VERBOSE: True
  IK_DIST_THRESH: 0.1
  IK_SPEED_FACTOR: 1.0

TASK_CONFIG:
    REWARD_MEASURE: "rearrange_reach_reward"
    SUCCESS_MEASURE: "rearrange_reach_success"
    SUCCESS_REWARD: 10.0
    SLACK_REWARD: -0.01
    END_ON_SUCCESS: False
    GYM:
      OBS_KEYS: ['joint', 'ee_pos']
      DESIRED_GOAL_KEYS: ['resting_position']
      FIX_INFO_DICT: True
      ACTION_KEYS: ['ARM_ACTION']
      CLASS_NAME: "RearrangeRLEnv"

VIDEO_DIR: "data/vids/"
VIDEO_OPTIONS: ["disk"]

COUNT_OBJ_COLLISIONS: True
COUNT_ROBOT_OBJ_COLLS: False
