# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: objectnav_v2
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_agent
  - /habitat/dataset/objectnav: hm3d_v2
  - _self_

habitat:
  environment:
    max_episode_seconds: 500

  simulator:
    action_space_config: "velocitycontrol"
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 480
            height: 640
            hfov: 42
            position: [0, 1.31, 0]
          depth_sensor:
            width: 480
            height: 640
            hfov: 42
            min_depth: 0.5
            max_depth: 5.0
            position: [0, 1.31, 0]
        height: 1.41
        radius: 0.17
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False
