# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbdp_head_rgb_third_agent
  - /habitat/task/rearrange: cat_pick
  - /habitat/dataset/rearrangement: floorplanner
  - _self_

habitat:
  gym:
    auto_name: Pick
    obs_keys:
      - robot_head_rgb
      - robot_head_depth
      - object_embedding
      - joint
      - is_holding
      - relative_resting_position
  environment:
    max_episode_steps: 300
  simulator:
    type: ObjectRearrangeSim-v0
    additional_object_paths:
      - data/objects/ycb/configs/
      - data/objects/amazon_berkeley/configs/
      - data/objects/google_object_dataset/configs/
    needs_markers: False
    concur_render: True
    auto_sleep: True
    agents:
      main_agent:
        radius: 0.25
        robot_urdf: data/robots/hab_stretch/urdf/hab_stretch.urdf
        robot_type: "StretchRobot"
        sim_sensors:
           head_rgb_sensor:
             height: 256
             width: 256
             hfov: 42
           head_depth_sensor:
             height: 256
             width: 256
             hfov: 42
           head_panoptic_sensor:
             height: 256
             width: 256
             hfov: 42
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True

  dataset:
    data_path: data/datasets/floorplanner/rearrange/v1/{split}/categorical_rearrange_easy.json.gz
    type: ObjectRearrangeDataset-v0
