# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbdp_head_rgb_third_agent
  - /habitat/task/rearrange: modular_cat_nav_to_obj
  - /habitat/dataset/rearrangement: floorplanner
  - _self_

habitat:
  seed: 7
  gym:
    auto_name: NavToObj
    obs_keys:
      - robot_head_depth
      - robot_head_rgb
      - robot_third_rgb
      - start_receptacle
      - goal_receptacle
      - robot_start_gps
      - robot_start_compass
      - joint
      - object_segmentation
      - start_recep_segmentation
      - goal_recep_segmentation
      - object_category
      - camera_pose
      - object_embedding
      - is_holding
      - relative_resting_position
  environment:
    max_episode_steps: 400
  simulator:
    type: ObjectRearrangeSim-v0
    additional_object_paths:
      - data/objects/ycb/configs/
      - data/objects/amazon_berkeley/configs/
      - data/objects/google_object_dataset/configs/
    debug_render_goal: False
    concur_render: True
    auto_sleep: True
    kinematic_mode: True
    agents:
      main_agent:
        radius: 0.25
        robot_urdf: data/robots/hab_stretch/urdf/hab_stretch.urdf
        robot_type: "StretchRobot"
        sim_sensors:
           head_rgb_sensor:
             height: 640
             width: 480
             hfov: 42
           head_depth_sensor:
             height: 640
             width: 480
             hfov: 42
           head_panoptic_sensor:
             height: 640
             width: 480
             hfov: 42
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True
    needs_markers: false
  dataset:
    data_path: data/episodes/rearrange/minival/cat_rearrange_floorplanner.json.gz
    type: ObjectRearrangeDataset-v0
  task:
    goal_type: 'ovmm'
