# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: depth_head_agent
  - /habitat/task/rearrange: nav_to_obj
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  gym:
    auto_name: NavToObj
    obs_keys:
      - robot_head_depth
      - goal_to_agent_gps_compass
      - joint
  environment:
    max_episode_steps: 400
  simulator:
    type: RearrangeSim-v0
    additional_object_paths:
      - data/objects/ycb/configs/
    debug_render_goal: False
    concur_render: True
    auto_sleep: True
    agents:
      main_agent:
        radius: 0.3
        robot_urdf: ./data/robots/hab_fetch/robots/hab_suction.urdf
        robot_type: FetchSuctionRobot
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True
    needs_markers: false
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/rearrange_easy.json.gz
