# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task/actions:
    - humanoidjoint_action
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_head_rgbd_arm_agent
  - /habitat/task/rearrange: play_human
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

# Config for empty task to explore the scene.
habitat:
  environment:
    max_episode_steps: 0
  simulator:
    type: RearrangeSim-v0
    seed: 100
    additional_object_paths:
      - "data/objects/ycb/configs/"
    agents:
      main_agent:
        radius: 0.3
        articulated_agent_urdf: 'data/humanoids/humanoid_data/female2_0.urdf'
        articulated_agent_type: 'KinematicHumanoid'
        rest_pose_data_path: 'data/humanoids/humanoid_data/standing_pose_smplx.pkl'
        sim_sensors:
          head_rgb_sensor:
            height: 128
            width: 128
          head_depth_sensor:
            height: 128
            width: 128
          arm_depth_sensor:
            height: 128
            width: 128
          arm_rgb_sensor:
            height: 128
            width: 128
    habitat_sim_v0:
      enable_physics: True
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/all_receptacles_10k_1k.json.gz
