[tool.black]
line_length = 79
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | ^examples/tutorials/notebooks
    | ^examples/tutorials/nb_python
    | build
    | dist
    | obselete
    | deps
  )/
)
'''

[tool.ty.environment]
extra-paths = [
    "habitat-lab",
    "habitat-baselines"
]
root = [
    "habitat-lab",
    "habitat-baselines"
]

[tool.ty.rules]
unresolved-attribute = "ignore"

[tool.pyrefly]
search-path = [
    "habitat-lab",
    "habitat-baselines"
]
