# @package habitat.dataset

defaults:
  - /habitat/dataset: object_rearrange_dataset_config_schema
  - _self_

type: RearrangeDataset-v0
split: minitrain
data_path: data/datasets/floorplanner/rearrange/v2/{split}/cat_rearrange_floorplanner.json.gz
scenes_dir: "data/fpss/fphab"
viewpoints_matrix_path: data/datasets/floorplanner/rearrange/v2/{split}/cat_rearrange_floorplanner_viewpoints_matrix.npy
transformations_matrix_path: data/datasets/floorplanner/rearrange/v2/{split}/cat_rearrange_floorplanner_transformations_matrix.npy
