# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: RearrangeDataset-v0
split: train
data_path: data/datasets/floorplanner/rearrange/v1/{split}/rearrange_easy.json.gz
scenes_dir: "data/fpss/fphab/"
