# @package habitat.dataset

defaults:
  - /habitat/dataset: object_rearrange_dataset_config_schema
  - _self_

type: OVMMDataset-v0
split: train
data_path: data/episodes/rearrange/v4/{split}/cat_npz-exp.json.gz
scenes_dir: "data/fphab/fphab/"
viewpoints_matrix_path: data/episodes/rearrange/v4/{split}/cat_npz-exp-vps.npy
transformations_matrix_path: data/episodes/rearrange/v4/{split}/cat_npz-exp-trans.npy
