# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: imagenav
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_agent
  - _self_

habitat:
  environment:
    max_episode_steps: 1000
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
          depth_sensor:
            width: 256
            height: 256
