# @package _global_

defaults:

  - /benchmark/rearrange/hab3_bench: multi_agent_bench
  - /habitat/task/lab_sensors:
    - relative_resting_pos_sensor
    - target_start_sensor
    - goal_sensor
    - joint_sensor
    - is_holding_sensor
    - end_effector_sensor
    - target_start_gps_compass_sensor
    - target_goal_gps_compass_sensor
    - localization_sensor
    - humanoid_joint_sensor
    - has_finished_oracle_nav
  - /habitat/task/actions@habitat.task.actions.agent_1_oracle_nav_action: oracle_nav_action
  - /habitat/task/actions@habitat.task.actions.agent_0_oracle_nav_action: oracle_nav_action
  # For Spot observation space
  - _self_


habitat:
  gym:
    obs_keys:
      - agent_0_head_depth
      - agent_0_relative_resting_position
      - agent_0_obj_start_sensor
      - agent_0_obj_goal_sensor
      - agent_0_obj_start_gps_compass
      - agent_0_obj_goal_gps_compass
      - agent_0_joint
      - agent_0_is_holding
      - agent_0_ee_pos
      - agent_0_localization_sensor
      - agent_0_other_agent_gps
      - agent_0_has_finished_oracle_nav
      - agent_1_head_depth
      - agent_1_relative_resting_position
      - agent_1_obj_start_sensor
      - agent_1_obj_goal_sensor
      - agent_1_obj_start_gps_compass
      - agent_1_obj_goal_gps_compass
      - agent_1_is_holding
      - agent_1_ee_pos
      - agent_1_localization_sensor
      - agent_1_joint
      - agent_1_other_agent_gps
      - agent_1_has_finished_oracle_nav
