name: "HierarchicalPolicy"
obs_transforms:
  add_virtual_keys:
    virtual_keys:
      "goal_to_agent_gps_compass": 2
hierarchical_policy:
  high_level_policy:
    name: 
      _target_: "habitat_baselines.rl.multi_agent.policies.NeuralHighLevelPolicy"
    allowed_actions:
      - nav_to_goal
      - nav_to_obj
      - pick
      - place
      #- nav_to_receptacle_by_name
    allow_other_place: False
    hidden_dim: 512
    use_rnn: True
    rnn_type: 'LSTM'
    backbone: resnet18
    normalize_visual_inputs: False
    num_rnn_layers: 2
    termination_obs_name: null
    replan_dist: -1.0
  defined_skills: {}
