
name: "HierarchicalPolicy"
obs_transforms:
  add_virtual_keys:
    virtual_keys:
      "goal_to_agent_gps_compass": 2
hierarchical_policy:
  high_level_policy:
    name: "FixedHighLevelPolicy"
    add_arm_rest: True
  
  defined_skills:
    open_cab:
      skill_name: "NoopSkillPolicy"
      max_skill_steps: 1
      apply_postconds: True

    open_fridge:
      skill_name: "NoopSkillPolicy"
      max_skill_steps: 1
      apply_postconds: True

    close_cab:
      skill_name: "NoopSkillPolicy"
      obs_skill_inputs: ["obj_start_sensor"]
      max_skill_steps: 1

    close_fridge:
      skill_name: "NoopSkillPolicy"
      obs_skill_inputs: ["obj_start_sensor"]
      max_skill_steps: 1
      apply_postconds: True

    pick:
      skill_name: "NoopSkillPolicy"
      obs_skill_inputs: ["obj_start_sensor"]
      max_skill_steps: 1
      apply_postconds: True
      force_end_on_timeout: False

    place:
      skill_name: "NoopSkillPolicy"
      obs_skill_inputs: ["obj_goal_sensor"]
      max_skill_steps: 1
      apply_postconds: True
      force_end_on_timeout: False

    nav_to_obj:
      skill_name: "OracleNavPolicy"
      obs_skill_inputs: ["obj_start_sensor", "abs_obj_start_sensor", "obj_goal_sensor", "abs_obj_goal_sensor"]
      max_skill_steps: 300

    wait_skill:
      skill_name: "WaitSkillPolicy"
      max_skill_steps: -1
      force_end_on_timeout: False

    reset_arm_skill:
      skill_name: "ResetArmSkill"
      max_skill_steps: 50
      reset_joint_state: [-4.50e-01, -1.07e00, 9.95e-02, 9.38e-01, -7.88e-04, 1.57e00, 4.62e-03]
      force_end_on_timeout: False

  use_skills:
    open_cab: "open_cab"
    open_fridge: "open_fridge"
    close_cab: "close_cab"
    close_fridge: "close_fridge"
    pick: "pick"
    place: "place"
    nav: "nav_to_obj"
    nav_to_receptacle: "nav_to_obj"
    wait: "wait_skill"
    reset_arm: "reset_arm_skill"
