# Oracle skills that will teleport to the skill post-condition. When automatically setting predicates you may want to run the simulation in kinematic mode:
# To run in kinematic mode, add: `habitat.simulator.kinematic_mode=True habitat.simulator.ac_freq_ratio=1`

# pick:
#   skill_name: "NoopHumanSkillPolicy"
#   obs_skill_inputs: ["obj_start_sensor"]
#   max_skill_steps: 1
#   apply_postconds: True
#   force_end_on_timeout: False

pick:
  skill_name: "HumanPickSkillPolicy"
  obs_skill_inputs: ["obj_start_sensor"]
  max_skill_steps: 20
  apply_postconds: True
  force_end_on_timeout: False


place:
  skill_name: "HumanPlaceSkillPolicy"
  obs_skill_inputs: ["obj_start_sensor"]
  max_skill_steps: 20
  apply_postconds: True
  force_end_on_timeout: False

wait:
  skill_name: "HumanWaitSkillPolicy"
  max_skill_steps: -1
  force_end_on_timeout: False

# reset_arm:
#   skill_name: "ResetArmHumanSkill"
#   obs_skill_inputs: ["obj_start_sensor"]
#   max_skill_steps: 10
#   force_end_on_timeout: False


reset_arm:
  skill_name: "NoopHumanSkillPolicy"
  obs_skill_inputs: ["obj_start_sensor"]
  max_skill_steps: 10
  force_end_on_timeout: False