# @package habitat.dataset
defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: ObjectNav-v1
split: train
data_path: data/datasets/objectnav/hssd-hab_v0.2.3/{split}/{split}.json.gz
