# @package habitat.dataset
defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: ObjectNav-v1
split: train
data_path: data/datasets/objectnav/procthor-hab/{split}/{split}.json.gz
scenes_dir: data/scene_datasets/ai2thor-hab/ai2thor-hab/configs/scenes/ProcTHOR/
