# Hyperparameters and ResNet18 from on https://arxiv.org/abs/2012.0611

VERBOSE: False

BASE_TASK_CONFIG_PATH: "configs/tasks/multinav_mp3d.yaml"
TRAINER_NAME: "ppo"
ENV_NAME: "MultiONNavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 1
VIDEO_OPTION: []
# Can be uncommented to generate videos.
# VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
# Evaluate on all episodes
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "new_checkpoints"
NUM_ENVIRONMENTS: 1
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "new_checkpoints"
TOTAL_NUM_STEPS: -1.0
LOG_INTERVAL: 1
NUM_CHECKPOINTS: 100
# Force PyTorch to be single threaded as
# this improves performance considerably
FORCE_TORCH_SINGLE_THREADED: True

RL:
  REWARD_MEASURE: "distance_to_current_object_goal"
  SUCCESS_MEASURE: "multiON_success"
  CURRENT_GOAL_SUCCESS_MEASURE: "current_goal_success"
  SUCCESS_REWARD: 3.0
  PPO:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 4
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50

    # Use double buffered sampling, typically helps
    # when environment time is similar or large than
    # policy inference time during rollout generation
    use_double_buffered_sampler: False
