# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: InstanceImageNav-v1
split: train
data_path: data/datasets/instance_imagenav/hm3d/v2/{split}/{split}.json.gz
