# For more info about Hydra in Habitat, see habitat-lab/habitat/config/README.md
# @package _global_

habitat_hitl:
  driver: "SimDriver"
  disable_policies_and_stepping: True
  window: ~
  use_gpu: True
  networking:
    enable: True
    max_client_count: 1
    http_availability_server:
      enable: True
    # client_max_idle_duration: 180.0   # TODO: Set up AFK timers.
    enable_connections_by_default: False
  experimental:
    headless:
      do_headless: True
  client_sync:
    server_camera: False
    server_input: True
    skinning: True

isaac_robot_teleop:
  draw_debug_shapes: True
  camera_move_speed: 0.1
  lock_pc_camera_to_robot: True
  usd_scene_path: "../../../data/usd/scenes/"
  navmesh_path: "data/hssd-hab/navmeshes/"
  scene_name: "104348133_171513054_8"
  episode_dataset: "episodes/hitl_teleop_episodes_single_sugarbox.json.gz"
  episode_index: 0

  #physx configuration settings
  #applied to all rigid objects added to the scene (e.g. from Episodes)
  object_static_friction: 20
  object_dynamic_friction: 20
  object_restitution: 0
  #applied to the contents of the scene (architecture, furniture, etc...)
  stage_static_friction: 10
  stage_dynamic_friction: 10
  stage_restitution: 0

defaults:
  # Load default parameters for the HITL framework. See
  # habitat-hitl/habitat_hitl/config/hitl_defaults.yaml.
  - hitl_defaults
  - _self_
