BASE_TASK_CONFIG_PATH: "configs/tasks/eqa_mp3d.yaml"
TRAINER_NAME: "pacman"

ENV_NAME: "NavILEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0

ONLY_VQA_TASK: False # if True, only last `num_frames` will be saved to disk.
#if False, all frames for each episode are saved to disk (for NAV task later)
FRAME_DATASET_PATH: "data/datasets/eqa/frame_dataset/{split}"
EVAL_CKPT_PATH_DIR: "data/eqa/nav/checkpoints/"
EQA_CNN_PRETRAIN_CKPT_PATH: "data/eqa/eqa_cnn_pretrain/checkpoints/epoch_5.ckpt"

NUM_PROCESSES: 1
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/eqa/nav/checkpoints"
TENSORBOARD_DIR: "data/eqa/nav/tb"
RESULTS_DIR: "data/eqa/nav/results/{split}"

LOG_METRICS: True
OUTPUT_LOG_DIR: data/eqa/nav/logs
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 1
EVAL_SAVE_RESULTS: True
EVAL_SAVE_RESULTS_INTERVAL: 10
# Force PyTorch to be single threaded as
# this improves performance considerably
FORCE_TORCH_SINGLE_THREADED: True

IL:
  NAV:
    # nav params
    max_epochs: 20
    batch_size: 20
    lr: 1e-3
    max_controller_actions: 5
    max_episode_length: 100
