BASE_TASK_CONFIG_PATH: "configs/tasks/eqa_mp3d.yaml"
TRAINER_NAME: "vqa"

ENV_NAME: "VQAILEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0

ONLY_VQA_TASK: False # if True, only last `num_frames` will be saved to disk.
#if False, all frames for each episode are saved to disk (for NAV task later)
DATASET_PATH: "data/datasets/eqa/frame_dataset/{split}/{split}.db"
FRAME_DATASET_PATH: "data/datasets/eqa/frame_dataset/{split}"
EVAL_CKPT_PATH_DIR: "data/eqa/vqa/checkpoints/"
EQA_CNN_PRETRAIN_CKPT_PATH: "data/eqa/eqa_cnn_pretrain/checkpoints/epoch_5.ckpt"

SENSORS: ["RGB_SENSOR"]
CHECKPOINT_FOLDER: "data/eqa/vqa/checkpoints/"
TENSORBOARD_DIR: "data/eqa/vqa/tb"
RESULTS_DIR: "data/eqa/vqa/results/{split}"

LOG_METRICS: True
OUTPUT_LOG_DIR: "data/eqa/vqa/logs"
LOG_INTERVAL: 100
EVAL_SAVE_RESULTS: True
EVAL_SAVE_RESULTS_INTERVAL: 10

# Force PyTorch to be single threaded as
# this improves performance considerably
FORCE_TORCH_SINGLE_THREADED: True

IL:
  VQA:
    # vqa params
    num_frames: 5
    max_epochs: 50
    batch_size: 20
    lr: 3e-4
    freeze_encoder: False
