# @package habitat.simulator.agents.rgbds_agent

defaults:
  - /habitat/simulator/sim_sensors@sim_sensors.rgb_sensor: rgb_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.depth_sensor: depth_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.semantic_sensor: semantic_sensor
