# @package _global_

defaults:
  - /rearrange/rl_hierarchical_humanoid
  - override /habitat_baselines/rl/policy: hl_neural
  - _self_

habitat_baselines:
  video_dir: ${hydra:sweep.dir}/${hydra:sweep.subdir}/video
  tensorboard_dir: ${hydra:sweep.dir}/${hydra:sweep.subdir}/tb
  eval_ckpt_path_dir: ${hydra:sweep.dir}/${hydra:sweep.subdir}/checkpoints
  checkpoint_folder: ${hydra:sweep.dir}/${hydra:sweep.subdir}/checkpoints
  log_file: ${hydra:sweep.dir}/${hydra:sweep.subdir}/train.log
  evaluate: False
  writer_type: 'wb'
  wb:
    project_name: 'hab3'
    entity: 'andrew-colab'
  num_environments: 2

habitat:
  task:
    measurements:
      composite_success:
        must_call_stop: False
      force_terminate:
        max_accum_force: -1.0
        max_instant_force: -1.0

  environment:
    max_episode_steps: 30

  simulator:
    kinematic_mode: True
    ac_freq_ratio: 1
    step_physics: False

