# @package _global_

defaults:
  - /rearrange/rl_hierarchical_oracle_nav
  - override /habitat_baselines/rl/policy@habitat_baselines.rl.policy.main_agent: hab3_hl_neural
  - override /habitat_baselines/rl/policy/hierarchical_policy/defined_skills@habitat_baselines.rl.policy.main_agent.hierarchical_policy.defined_skills: oracle_skills
  - _self_

hydra:
  job:
    name: 'single_oracle'

habitat_baselines:
  log_interval: 1
  video_dir: ${hydra:sweep.dir}/${hydra:sweep.subdir}/video
  tensorboard_dir: ${hydra:sweep.dir}/${hydra:sweep.subdir}/tb
  eval_ckpt_path_dir: ${hydra:sweep.dir}/${hydra:sweep.subdir}/checkpoints
  checkpoint_folder: ${hydra:sweep.dir}/${hydra:sweep.subdir}/checkpoints
  log_file: ${hydra:sweep.dir}/${hydra:sweep.subdir}/train.log
  evaluate: False
  writer_type: 'wb'
  wb:
    project_name: 'hab3'
    entity: 'andrew-colab'
    run_name: ${hydra:job.name}_${now:%Y-%m-%d}_${now:%H-%M-%S}
  num_environments: 2

habitat:
  task:
    actions:
      oracle_nav_action:
        spawn_max_dist_to_obj: -1.0
    measurements:
      composite_success:
        must_call_stop: False
      force_terminate:
        max_accum_force: -1.0
        max_instant_force: -1.0

  environment:
    max_episode_steps: 700

  simulator:
    kinematic_mode: True
    ac_freq_ratio: 1
    step_physics: False
