# @package habitat.simulator.agents.rgb_head_agent

defaults:
  - agent_base
  - /habitat/simulator/sim_sensors@sim_sensors.head_rgb_sensor: head_rgb_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.head_depth_sensor: head_depth_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.head_semantic_sensor: head_semantic_sensor
