# @package habitat.simulator.agents.rgb_head_agent

defaults:
  - agent_base
  - /habitat/simulator/sim_sensors@sim_sensors.head_rgb_sensor: head_rgb_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.head_depth_sensor: head_depth_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.head_panoptic_sensor: head_panoptic_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.third_rgb_sensor: third_rgb_sensor
