# @package habitat.simulator.agents.spot
defaults:
  - agent_base
  - _self_

radius: 0.25
height: 1.41
articulated_agent_type: "SpotRobotReal"
articulated_agent_urdf: data/robots/hab_spot_arm/urdf/hab_spot_arm.urdf
ik_arm_urdf: data/robots/hab_spot_arm/urdf/spot_onlyarm.urdf