TASK:
  TYPE: EQA-v0
  SENSORS: ['QUESTION_SENSOR']
  POSSIBLE_ACTIONS: ['MOVE_FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'ANSWER']
  MEASUREMENTS: ['EPISODE_INFO', 'DISTANCE_TO_GOAL', 'ANSWER_ACCURACY']

ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'SEMANTIC_SENSOR', 'DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  SEMANTIC_SENSOR:
    WIDTH: 256
    HEIGHT: 256

DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/rearrange_pick/replica_cad/v0/{split}/{split}_counter_L_analysis_5000_500.json.gz
    SCENES_DIR: "data/replica_cad/"