ENVIRONMENT:
  MAX_EPISODE_STEPS: 1000
  ITERATOR_OPTIONS:
    MAX_SCENE_REPEAT_STEPS: 50000
SIMULATOR:
  AGENT_0:
    SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0

  SENSORS: ['IMAGEGOAL_SENSOR']

  MEASUREMENTS: ["DISTANCE_TO_GOAL", "SUCCESS", "SPL", "SOFT_SPL"]
  SUCCESS:
    SUCCESS_DISTANCE: 1.

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz
