ENVIRONMENT:
  MAX_EPISODE_STEPS: 1000

SIMULATOR:
  TYPE: "RearrangementSim-v0"
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "RearrangementActions-v0"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
  GRAB_DISTANCE: 2.0
  HABITAT_SIM_V0.ENABLE_PHYSICS: True

TASK:
  TYPE: RearrangementTask-v0
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "GRAB_RELEASE"]
  SUCCESS_DISTANCE: 0.1

  SENSORS: ["GRIPPED_OBJECT_SENSOR", "ALL_OBJECT_POSITIONS", "ALL_OBJECT_GOALS"]
  GOAL_SENSOR_UUID: object_goal

  MEASUREMENTS: ['OBJECT_TO_GOAL_DISTANCE', 'AGENT_TO_OBJECT_DISTANCE']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2
  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS

DATASET:
  TYPE: RearrangementDataset-v0
  SPLIT: train
  CONTENT_SCENES: ["rearrangement_obj_5_scene_28_episode_1_gibson"]
  DATA_PATH: "data/datasets/rearrangement/gibson/v1/{split}/{split}.json.gz"
