ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 15
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 45
    TYPE: HabitatSimRGBSensor
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: VLN-v0
  SUCCESS_DISTANCE: 3.0
  SENSORS: ['INSTRUCTION_SENSOR']
  POSSIBLE_ACTIONS: ['MOVE_FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'STOP']
  MEASUREMENTS: ['SPL']
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 3.0
DATASET:
  TYPE: R2RVLN-v1
  SPLIT: train
  DATA_PATH: "data/datasets/vln/r2r/v1/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"
