# @package habitat.task

defaults:
  - /habitat/task: task_config_base
  - /habitat/task/actions:
    - arm_action
    - base_velocity
  - /habitat/task/measurements:
    - robot_force
    - force_terminate
    - robot_colls
    - end_effector_to_rest_distance
    - end_effector_to_goal_distance
    - object_to_goal_distance
    - obj_anywhere_on_goal
    - place_success
    - place_reward
    - num_steps
  - /habitat/task/lab_sensors:
    - joint_sensor
    - joint_velocity_sensor
    - is_holding_sensor
    - end_effector_sensor
    - cat_nav_goal_segmentation_sensor
    - receptacle_segmentation_sensor
    - relative_resting_pos_sensor
    - goal_receptacle_sensor
  - _self_

type: RearrangePlaceTask-v0
base_angle_noise: 0.523599
constraint_violation_ends_episode: False
constraint_violation_drops_object: True
reward_measure: place_reward
success_measure: place_success
success_reward: 10.0
slack_reward: -0.005
spawn_reference: view_points
spawn_max_dists_to_obj: 0.0
end_on_success: True
desired_resting_position: [0.119, -0.383, 0.657]
actions:
  arm_action:
    type: "ArmAction"
    arm_controller: "ArmRelPosReducedActionStretch"
    grip_controller: "MagicGraspAction"
    arm_joint_mask: [1,0,0,0,1,1,1,1,0,0]
    arm_joint_dimensionality: 5
    grasp_thresh_dist: 0.15
    disable_grip: False
    delta_pos_limit: 0.0125
    ee_ctrl_lim: 0.015
  base_velocity:
    type: "BaseWaypointTeleportAction"
    navmesh_offset: [[0.0, 0.0]]

measurements:
  force_terminate:
    max_accum_force: 10_000.0
    max_instant_force: 10_000.0
  place_success:
    place_anywhere: True
  place_reward:
    place_anywhere: True
    sparse_reward: False
lab_sensors:
  joint_sensor:
    dimensionality: 10
  joint_velocity_sensor:
    dimensionality: 10
