# @package habitat.task

defaults:
  - /habitat/task: task_config_base
  - /habitat/task/actions:
    - rearrange_stop
    - base_velocity
    - arm_action
    - extend_arm
    - face_arm
    - reset_joints
  - /habitat/task/measurements:
    - object_to_goal_distance
    - robot_force
    - force_terminate
    - robot_colls
    - rot_dist_to_goal
    - dist_to_goal
    # TODO: inconsistent naming succ vs succcess, rearrange prefix
    - nav_to_pos_succ
    - does_want_terminate
    - rearrange_nav_to_obj_success
    - bad_called_terminate
    - rearrange_nav_to_obj_reward
    - num_steps
    - obj_anywhere_on_goal
    - end_effector_to_rest_distance
    - did_pick_object
    - pick_success
    - place_success
    - pick_nav_to_pos_succ
    - rearrange_pick_nav_to_obj_success
  - /habitat/task/lab_sensors:
    - joint_sensor
    - joint_velocity_sensor
    - object_category_sensor
    - start_receptacle_sensor
    - goal_receptacle_sensor
    - object_segmentation_sensor
    - object_embedding_sensor
    - start_recep_segmentation_sensor
    - goal_recep_segmentation_sensor
    - robot_start_gps_sensor
    - robot_start_compass_sensor
    - camera_pose_sensor
    - end_effector_sensor
    - relative_resting_pos_sensor
    - is_holding_sensor
  - _self_

type: CatNavToObjTask-v0
reward_measure: nav_to_obj_reward
success_measure: nav_to_obj_success
success_reward: 10.0
slack_reward: -0.005
end_on_success: True
constraint_violation_ends_episode: False
constraint_violation_drops_object: True
object_in_hand_sample_prob: 0.0
actions:
  arm_action:
    type: "ArmAction"
    arm_controller: "ArmRelPosReducedActionStretch"
    grip_controller: "OracleGraspAction"
    arm_joint_mask: [1,0,0,0,1,1,1,1,1,1]
    arm_joint_dimensionality: 7
    grasp_thresh_dist: 0.15
    disable_grip: False
    delta_pos_limit: 0.0125
    ee_ctrl_lim: 0.015
  base_velocity:
    type: "BaseWaypointVelAction"
    lin_speed: 0.2500
    ang_speed: 0.1745
    allow_dyn_slide: False
measurements:
  force_terminate:
    max_accum_force: -1.0
    max_instant_force: -1.0
  pick_success: 
    object_goal: True
    ee_resting_success_threshold: 100
  place_success:
    place_anywhere: True
    ee_resting_success_threshold: 100
lab_sensors:
  joint_sensor:
    dimensionality: 10
  joint_velocity_sensor:
    dimensionality: 10