# @package habitat.task
defaults:
  - /habitat/task/rearrange: multi_agent_tidy_house_base
  - /habitat/task/actions@actions.agent_0_arm_action: arm_action
  - /habitat/task/actions@actions.agent_1_arm_action: arm_action
  - _self_

task_spec: multi_agent_tidy_house_fp_2obj
pddl_domain_def: fp

actions:
  # Actions are defined per agent. Unlike the sensors, actions are not
  # automatically duplicated per agent.
  agent_0_arm_action:
    grip_controller: MagicGraspAction
  agent_1_arm_action:
    grip_controller: MagicGraspAction
    agent_index : 1
