# Version of tidy house that only has two target objects.
objects:
  - name: any_targets|0
    expr_type: movable_entity_type
  - name: TARGET_any_targets|0
    expr_type: goal_entity_type
  - name: any_targets|1
    expr_type: movable_entity_type
  - name: TARGET_any_targets|1
    expr_type: goal_entity_type
  - name: any_targets|2
    expr_type: movable_entity_type
  - name: TARGET_any_targets|2
    expr_type: goal_entity_type
  - name: robot_0
    expr_type: robot_entity_type

goal:
  expr_type: AND
  sub_exprs:
    - at(any_targets|0,TARGET_any_targets|0)
    - at(any_targets|1,TARGET_any_targets|1)
    - at(any_targets|1,TARGET_any_targets|2)
    - not_holding(robot_0)

stage_goals:
  stage_1:
    expr_type: AND
    sub_exprs:
      - at(any_targets|0,TARGET_any_targets|0)
  stage_2:
    expr_type: AND
    sub_exprs:
      - at(any_targets|1,TARGET_any_targets|1)
  stage_3:
    expr_type: AND
    sub_exprs:
      - at(any_targets|1,TARGET_any_targets|2)

solution:
  - nav_to_obj(any_targets|0, robot_0)
  - pick(any_targets|0, robot_0)
  - nav_to_goal(TARGET_any_targets|0, robot_0)
  - place(any_targets|0,TARGET_any_targets|0, robot_0)
  - nav_to_obj(any_targets|1, robot_0)
  - pick(any_targets|1, robot_0)
  - nav_to_goal(TARGET_any_targets|1, robot_0)
  - place(any_targets|1,TARGET_any_targets|1, robot_0)
