# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 2160
nodes: 1
cpus_per_task: 10
mem_per_cpu: 5
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: devlab
tasks_per_node: 2 #make sure that tasks_per_node and gres are the same
gres: gpu:2
setup:
  - export MAIN_ADDR=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
  - export MASTER_ADDR=$(hostname -s)
  - export MAGNUM_LOG=quiet
  - export HABITAT_SIM_LOG=quiet
