GYM:
    AUTO_NAME: NavToObj
    OBS_KEYS:
    - robot_head_depth
    - goal_to_agent_gps_compass
    - joint
ENVIRONMENT:
    MAX_EPISODE_STEPS: 400
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/{split}/rearrange_easy.json.gz
    SCENES_DIR: data/replica_cad/
TASK:
    TYPE: NavToObjTask-v0

    # Spawn params
    OBJECT_IN_HAND_SAMPLE_PROB: 0.167
    MIN_START_DISTANCE: 3.0
    FORCE_REGENERATE: false
    SHOULD_SAVE_TO_CACHE: False

    CONSTRAINT_VIOLATION_ENDS_EPISODE: false
    CONSTRAINT_VIOLATION_DROPS_OBJECT: true
    COUNT_OBJ_COLLISIONS: true
    COUNT_ROBOT_OBJ_COLLS: false

    REWARD_MEASURE: nav_to_obj_reward
    SUCCESS_MEASURE: nav_to_obj_success
    SUCCESS_REWARD: 10.0
    SLACK_REWARD: -0.005
    END_ON_SUCCESS: true
    JOINT_SENSOR:
        TYPE: JointSensor
        DIMENSIONALITY: 7
    SENSORS:
    - TARGET_START_POINT_GOAL_SENSOR
    - JOINT_SENSOR
    FORCE_TERMINATE:
        TYPE: ForceTerminate
        MAX_ACCUM_FORCE: 10_000.0
        MAX_INSTANT_FORCE: 10_000.0

    REARRANGE_NAV_TO_OBJ_REWARD:
        TYPE: NavToObjReward
        SHOULD_REWARD_TURN: true
        TURN_REWARD_DIST: 3.0

        ANGLE_DIST_REWARD: 1.0
        DIST_REWARD: 1.0
        CONSTRAINT_VIOLATE_PEN: 1.0
        FORCE_PEN: 0.0001
        MAX_FORCE_PEN: 0.01
        FORCE_END_PEN: 1.0

    # Success criteria
    NAV_TO_POS_SUCC:
        TYPE: NavToPosSucc
        SUCCESS_DISTANCE: 1.5

    REARRANGE_NAV_TO_OBJ_SUCCESS:
        TYPE: NavToObjSuccess
        MUST_LOOK_AT_TARG: true
        SUCCESS_ANGLE_DIST: 0.261799 # 15 degrees.
        MUST_CALL_STOP: True
    MEASUREMENTS:
    - ROBOT_FORCE
    - FORCE_TERMINATE
    - ROBOT_COLLS
    - DOES_WANT_TERMINATE
    - ROT_DIST_TO_GOAL
    - DIST_TO_GOAL
    - NAV_TO_POS_SUCC
    - REARRANGE_NAV_TO_OBJ_SUCCESS
    - BAD_CALLED_TERMINATE
    - REARRANGE_NAV_TO_OBJ_REWARD
    - NUM_STEPS
    POSSIBLE_ACTIONS:
    - BASE_VELOCITY
    - REARRANGE_STOP
SIMULATOR:
    ADDITIONAL_OBJECT_PATHS:
    - data/objects/ycb/configs/
    DEBUG_RENDER: false
    DEBUG_RENDER_GOAL: false
    CONCUR_RENDER: True
    AUTO_SLEEP: True
    AGENTS:
    - AGENT_0
    AGENT_0:
        HEIGHT: 1.5
        RADIUS: 0.3
        JOINT_START_NOISE: 0.2
        SENSORS:
        - HEAD_DEPTH_SENSOR
        ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_suction.urdf
        ROBOT_TYPE: FetchSuctionRobot
        IK_ARM_URDF: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
    HEAD_DEPTH_SENSOR:
        WIDTH: 256
        HEIGHT: 256
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: true
    HABITAT_SIM_V0:
        ALLOW_SLIDING: false
        ENABLE_PHYSICS: true
        GPU_DEVICE_ID: 0
        GPU_GPU: false
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    TYPE: RearrangeSim-v0
    NEEDS_MARKERS: false
    ARM_DEPTH_SENSOR:
        WIDTH: 128
        HEIGHT: 128
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: true
    HEAD_RGB_SENSOR:
        WIDTH: 256
        HEIGHT: 256
    ARM_RGB_SENSOR:
        HEIGHT: 128
        WIDTH: 128
