GYM:
    CLASS_NAME: RearrangeRLEnv
    AUTO_NAME: NavPick
    OBS_KEYS:
    - robot_head_depth
    - obj_start_sensor
    - obj_start_gps_compass
    - joint
    - is_holding
ENVIRONMENT:
    MAX_EPISODE_STEPS: 500
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/{split}/all_receptacles_10k_1k.json.gz
    SCENES_DIR: data/replica_cad/
TASK:
    TYPE: RearrangeCompositeTask-v0
    REWARD_MEASURE: move_obj_reward
    SUCCESS_MEASURE: composite_success
    SUCCESS_REWARD: 100.0
    SLACK_REWARD: -0.01
    END_ON_SUCCESS: true
    MAX_COLLISIONS: -1.0
    COUNT_OBJ_COLLISIONS: true
    COUNT_ROBOT_OBJ_COLLS: false
    DESIRED_RESTING_POSITION:
    - 0.5
    - 0.0
    - 1.0
    CONSTRAINT_VIOLATION_ENDS_EPISODE: false
    BASE_ANGLE_NOISE: 0.15
    BASE_NOISE: 0.05
    EASY_INIT: false
    TASK_SPEC_BASE_PATH: configs/tasks/rearrange/pddl/
    TASK_SPEC: nav_pick_nav_place
    PDDL_DOMAIN_DEF: configs/tasks/rearrange/pddl/replica_cad_domain.yaml
    OBJ_SUCC_THRESH: 0.3
    ART_SUCC_THRESH: 0.15
    SINGLE_EVAL_NODE: -1
    DEBUG_SKIP_TO_NODE: -1
    SKIP_NODES:
    - move_obj
    TARGET_START_SENSOR:
        TYPE: TargetStartSensor
        GOAL_FORMAT: CARTESIAN
        DIMENSIONALITY: 3
    GOAL_SENSOR:
        TYPE: GoalSensor
        GOAL_FORMAT: CARTESIAN
        DIMENSIONALITY: 3
    JOINT_SENSOR:
        TYPE: JointSensor
        DIMENSIONALITY: 7
    END_EFFECTOR_SENSOR:
        TYPE: EEPositionSensor
    IS_HOLDING_SENSOR:
        TYPE: IsHoldingSensor
    SENSORS:
    - TARGET_START_SENSOR
    - GOAL_SENSOR
    - JOINT_SENSOR
    - IS_HOLDING_SENSOR
    - END_EFFECTOR_SENSOR
    - TARGET_START_GPS_COMPASS_SENSOR
    - TARGET_GOAL_GPS_COMPASS_SENSOR
    FORCE_TERMINATE:
        TYPE: ForceTerminate
        MAX_ACCUM_FORCE: -1.0
    ROBOT_FORCE:
        TYPE: RobotForce
        MIN_FORCE: 20.0
    MEASUREMENTS:
    - OBJECT_TO_GOAL_DISTANCE
    - ROBOT_FORCE
    - FORCE_TERMINATE
    - ROBOT_COLLS
    - END_EFFECTOR_TO_OBJECT_DISTANCE
    - DOES_WANT_TERMINATE
    - COMPOSITE_SUCCESS
    - COMPOSITE_BAD_CALLED_TERMINATE
    - NUM_STEPS
    - DID_VIOLATE_HOLD_CONSTRAINT
    - MOVE_OBJECTS_REWARD
    ACTIONS:
        ARM_ACTION:
            TYPE: ArmAction
            ARM_CONTROLLER: ArmRelPosAction
            GRIP_CONTROLLER: MagicGraspAction
            ARM_JOINT_DIMENSIONALITY: 7
            GRASP_THRESH_DIST: 0.15
            DISABLE_GRIP: false
            DELTA_POS_LIMIT: 0.0125
            EE_CTRL_LIM: 0.015
        BASE_VELOCITY:
            TYPE: BaseVelAction
            LIN_SPEED: 10.0
            ANG_SPEED: 10.0
            ALLOW_DYN_SLIDE: true
            END_ON_STOP: false
            ALLOW_BACK: true
            MIN_ABS_LIN_SPEED: 1.0
            MIN_ABS_ANG_SPEED: 1.0
        REARRANGE_STOP:
            TYPE: RearrangeStopAction
    POSSIBLE_ACTIONS:
    - ARM_ACTION
    - BASE_VELOCITY
    - REARRANGE_STOP
    USING_SUBTASKS: false
    MOVE_OBJECTS_REWARD:
        TYPE: MoveObjectsReward
        PICK_REWARD: 1.0
        SUCCESS_DIST: 0.15
        SINGLE_REARRANGE_REWARD: 1.0
        DIST_REWARD: 1.0
        CONSTRAINT_VIOLATE_PEN: 10.0
        FORCE_PEN: 0.0
        MAX_FORCE_PEN: 1.0
        FORCE_END_PEN: 10.0
    TARGET_START_GPS_COMPASS_SENSOR:
        TYPE: TargetStartGpsCompassSensor
    TARGET_GOAL_GPS_COMPASS_SENSOR:
        TYPE: TargetGoalGpsCompassSensor
    REARRANGE_NAV_TO_OBJ_SUCCESS:
        TYPE: NavToObjSuccess
        SUCCESS_ANGLE_DIST: 0.7
        MUST_LOOK_AT_TARG: true
        HEURISTIC_STOP: false
        MUST_CALL_STOP: false
    NAV_TO_POS_SUCC:
        TYPE: NavToPosSucc
        SUCCESS_DISTANCE: 0.2
    PLACE_SUCCESS:
        TYPE: PlaceSuccess
        EE_RESTING_SUCCESS_THRESHOLD: 0.3
    PICK_SUCCESS:
        TYPE: RearrangePickSuccess
        EE_RESTING_SUCCESS_THRESHOLD: 0.3
SIMULATOR:
    ADDITIONAL_OBJECT_PATHS:
        - "data/objects/ycb/configs/"
    ACTION_SPACE_CONFIG: v0
    GRASP_IMPULSE: 1000.0
    HOLD_THRESH: 0.09
    AC_FREQ_RATIO: 4
    DEBUG_RENDER: false
    DEBUG_RENDER_GOAL: true
    AGENTS:
    - AGENT_0
    CONCUR_RENDER: true
    AUTO_SLEEP: true
    AGENT_0:
        HEIGHT: 1.5
        IS_SET_START_STATE: false
        RADIUS: 0.3
        SENSORS:
        - HEAD_DEPTH_SENSOR
        START_POSITION:
        - 0
        - 0
        - 0
        START_ROTATION:
        - 0
        - 0
        - 0
        - 1
    HEAD_RGB_SENSOR:
        WIDTH: 128
        HEIGHT: 128
    HEAD_DEPTH_SENSOR:
        WIDTH: 128
        HEIGHT: 128
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: true
    ARM_DEPTH_SENSOR:
        HEIGHT: 128
        MAX_DEPTH: 10.0
        MIN_DEPTH: 0.0
        NORMALIZE_DEPTH: true
        WIDTH: 128
    ARM_RGB_SENSOR:
        HEIGHT: 128
        WIDTH: 128
    ARM_REST:
    - 0.6
    - 0.0
    - 0.9
    CTRL_FREQ: 120.0
    DEFAULT_AGENT_ID: 0
    FORWARD_STEP_SIZE: 0.25
    HABITAT_SIM_V0:
        ALLOW_SLIDING: false
        ENABLE_PHYSICS: true
        GPU_DEVICE_ID: 0
        GPU_GPU: false
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_fetch.urdf
    ROBOT_TYPE: FetchRobot
    IK_ARM_URDF: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
    SEED: 100
    SEMANTIC_SENSOR:
        HEIGHT: 480
        HFOV: 90
        ORIENTATION:
        - 0.0
        - 0.0
        - 0.0
        POSITION:
        - 0
        - 1.25
        - 0
        TYPE: HabitatSimSemanticSensor
        WIDTH: 640
    TILT_ANGLE: 15
    TURN_ANGLE: 10
    TYPE: RearrangeSim-v0
