GYM:
    AUTO_NAME: OpenFridge
    OBS_KEYS:
    - robot_head_depth
    - joint
    - ee_pos
    - is_holding
    - relative_resting_position
ENVIRONMENT:
    MAX_EPISODE_STEPS: 200
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/{split}/in_fridge_1k_100.json.gz
    SCENES_DIR: data/replica_cad/
TASK:
    TYPE: RearrangeOpenFridgeTask-v0
    SETTLE_STEPS: 5
    BASE_ANGLE_NOISE: 0.15
    SPAWN_REGION_SCALE: 0.2
    JOINT_MAX_IMPULSE: -1.0

    CONSTRAINT_VIOLATION_ENDS_EPISODE: false
    CONSTRAINT_VIOLATION_DROPS_OBJECT: true
    COUNT_OBJ_COLLISIONS: true
    COUNT_ROBOT_OBJ_COLLS: false

    USE_MARKER_T: false
    SUCCESS_STATE: 1.2207963268
    REWARD_MEASURE: art_obj_reward
    SUCCESS_MEASURE: art_obj_success
    SUCCESS_REWARD: 10.0
    SLACK_REWARD: 0.0
    END_ON_SUCCESS: true
    EASY_INIT: false
    JOINT_SENSOR:
        TYPE: JointSensor
        DIMENSIONALITY: 7
    SENSORS:
    - JOINT_SENSOR
    - IS_HOLDING_SENSOR
    - END_EFFECTOR_SENSOR
    - RELATIVE_RESTING_POS_SENSOR
    FORCE_TERMINATE:
        TYPE: ForceTerminate
        MAX_ACCUM_FORCE: 20_000.0
        MAX_INSTANT_FORCE: 10_000.0

    ART_OBJ_REWARD:
        TYPE: ArtObjReward
        WRONG_GRASP_END: true
        WRONG_GRASP_PEN: 5.0
        GRASP_REWARD: 5.0
        ART_AT_DESIRED_STATE_REWARD: 5.0
        MARKER_DIST_REWARD: 1.0
        ART_DIST_REWARD: 10.0
        EE_DIST_REWARD: 1.0
        CONSTRAINT_VIOLATE_PEN: 1.0
        FORCE_PEN: 0.0
        MAX_FORCE_PEN: 1.0
        FORCE_END_PEN: 10.0
    MEASUREMENTS:
    - ROBOT_FORCE
    - FORCE_TERMINATE
    - ROBOT_COLLS
    - DOES_WANT_TERMINATE
    - END_EFFECTOR_TO_REST_DISTANCE
    - EE_DIST_TO_MARKER
    - ART_OBJ_AT_DESIRED_STATE
    - ART_OBJ_STATE
    - ART_OBJ_SUCCESS
    - ART_OBJ_REWARD
    - NUM_STEPS
    - BAD_CALLED_TERMINATE
    ACTIONS:
        ARM_ACTION:
            GRIP_CONTROLLER: SuctionGraspAction
            ARM_JOINT_DIMENSIONALITY: 7
    POSSIBLE_ACTIONS:
    - ARM_ACTION
    - BASE_VELOCITY
    - REARRANGE_STOP
SIMULATOR:
    ADDITIONAL_OBJECT_PATHS:
    - data/objects/ycb/configs/
    DEBUG_RENDER: false
    DEBUG_RENDER_GOAL: false
    CONCUR_RENDER: True
    AUTO_SLEEP: True
    AGENT_0:
        HEIGHT: 1.5
        RADIUS: 0.3
        JOINT_START_NOISE: 0.2
        SENSORS:
        - HEAD_DEPTH_SENSOR
        ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_suction.urdf
        ROBOT_TYPE: FetchSuctionRobot
        IK_ARM_URDF: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
    HEAD_DEPTH_SENSOR:
        WIDTH: 256
        HEIGHT: 256
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: true
    HABITAT_SIM_V0:
        ALLOW_SLIDING: false
        ENABLE_PHYSICS: true
        GPU_DEVICE_ID: 0
        GPU_GPU: false
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    TYPE: RearrangeSim-v0
    NEEDS_MARKERS: true
    HEAD_RGB_SENSOR:
        WIDTH: 256
        HEIGHT: 256
    ARM_RGB_SENSOR:
        HEIGHT: 128
        WIDTH: 128
