GYM:
    AUTO_NAME: "Pick"
    OBS_KEYS: ['robot_head_depth', 'obj_start_sensor', 'joint', 'is_holding', 'relative_resting_position']
ENVIRONMENT:
    MAX_EPISODE_STEPS: 300
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/{split}/rearrange_easy.json.gz
    SCENES_DIR: "data/replica_cad/"
TASK:
    TYPE: RearrangePickTask-v0
    COUNT_OBJ_COLLISIONS: True
    COUNT_ROBOT_OBJ_COLLS: False

    # SPAWN PARAMETERS
    BASE_ANGLE_NOISE: 0.523599 # 30 deg
    FORCE_REGENERATE: false
    SPAWN_MAX_DISTS_TO_OBJ: [2.0]
    PHYSICS_STABILITY_STEPS: 1
    NUM_SPAWN_ATTEMPTS: [200]
    SHOULD_SAVE_TO_CACHE: False

    CONSTRAINT_VIOLATION_ENDS_EPISODE: false
    CONSTRAINT_VIOLATION_DROPS_OBJECT: True

    REWARD_MEASURE: "rearrangepick_reward"
    SUCCESS_MEASURE: "rearrangepick_success"
    SUCCESS_REWARD: 10.0
    SLACK_REWARD: -0.005
    END_ON_SUCCESS: True

    JOINT_SENSOR:
        TYPE: "JointSensor"
        DIMENSIONALITY: 7

    SENSORS: ["TARGET_START_SENSOR", "JOINT_SENSOR", "IS_HOLDING_SENSOR", "END_EFFECTOR_SENSOR", "RELATIVE_RESTING_POS_SENSOR"]
    FORCE_TERMINATE:
        TYPE: ForceTerminate
        MAX_ACCUM_FORCE: 10_000.0
        MAX_INSTANT_FORCE: 10_000.0
    PICK_REWARD:
        TYPE: "RearrangePickReward"
        DIST_REWARD: 2.0
        PICK_REWARD: 2.0
        DROP_PEN: 0.5
        WRONG_PICK_PEN: 0.5
        USE_DIFF: True
        DROP_OBJ_SHOULD_END: True
        WRONG_PICK_SHOULD_END: True

        # General Rearrange Reward config
        CONSTRAINT_VIOLATE_PEN: 1.0
        FORCE_PEN: 0.0001
        MAX_FORCE_PEN: 0.01
        FORCE_END_PEN: 1.0

    MEASUREMENTS:
        - "ROBOT_FORCE"
        - "FORCE_TERMINATE"
        - "END_EFFECTOR_TO_REST_DISTANCE"
        - "END_EFFECTOR_TO_OBJECT_DISTANCE"
        - "DID_PICK_OBJECT"
        - "PICK_SUCCESS"
        - "PICK_REWARD"
        - "DID_VIOLATE_HOLD_CONSTRAINT"
        - "NUM_STEPS"
    ACTIONS:
        ARM_ACTION:
            GRIP_CONTROLLER: SuctionGraspAction
            ARM_JOINT_DIMENSIONALITY: 7
    POSSIBLE_ACTIONS:
        - ARM_ACTION
        - BASE_VELOCITY

SIMULATOR:
    ADDITIONAL_OBJECT_PATHS:
        - "data/objects/ycb/configs/"
    ACTION_SPACE_CONFIG: v0
    AGENTS: ['AGENT_0']
    DEBUG_RENDER: False
    DEBUG_RENDER_GOAL: False
    NEEDS_MARKERS: False
    CONCUR_RENDER: True
    AUTO_SLEEP: True
    AGENT_0:
        HEIGHT: 1.5
        RADIUS: 0.3
        JOINT_START_NOISE: 0.2
        SENSORS: ['HEAD_DEPTH_SENSOR']
        ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_suction.urdf
        ROBOT_TYPE: FetchSuctionRobot
        IK_ARM_URDF: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
    HEAD_DEPTH_SENSOR:
        WIDTH: 256
        HEIGHT: 256
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: True
    HEAD_RGB_SENSOR:
        WIDTH: 256
        HEIGHT: 256
    ARM_DEPTH_SENSOR:
        HEIGHT: 128
        MAX_DEPTH: 10.0
        MIN_DEPTH: 0.0
        NORMALIZE_DEPTH: true
        WIDTH: 128
    ARM_RGB_SENSOR:
        HEIGHT: 128
        WIDTH: 128

    HABITAT_SIM_V0:
        ALLOW_SLIDING: False
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    TYPE: RearrangeSim-v0
