GYM:
    AUTO_NAME: Place
    OBS_KEYS:
    - robot_head_depth
    - obj_goal_sensor
    - joint
    - is_holding
    - relative_resting_position
ENVIRONMENT:
    MAX_EPISODE_STEPS: 300
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/{split}/rearrange_easy.json.gz
    SCENES_DIR: data/replica_cad/
TASK:
    TYPE: RearrangePlaceTask-v0
    COUNT_OBJ_COLLISIONS: true
    COUNT_ROBOT_OBJ_COLLS: false

    # SPAWN PARAMETERS
    BASE_ANGLE_NOISE: 0.523599  # 30 deg
    FORCE_REGENERATE: false
    SPAWN_MAX_DISTS_TO_OBJ: [2.0]
    PHYSICS_STABILITY_STEPS: 1
    NUM_SPAWN_ATTEMPTS: [200]
    SHOULD_SAVE_TO_CACHE: False

    CONSTRAINT_VIOLATION_ENDS_EPISODE: false
    CONSTRAINT_VIOLATION_DROPS_OBJECT: true

    REWARD_MEASURE: place_reward
    SUCCESS_MEASURE: place_success
    SUCCESS_REWARD: 10.0
    SLACK_REWARD: -0.005
    END_ON_SUCCESS: true

    SENSORS:
    - TARGET_START_SENSOR
    - GOAL_SENSOR
    - JOINT_SENSOR
    - IS_HOLDING_SENSOR
    - END_EFFECTOR_SENSOR
    - RELATIVE_RESTING_POS_SENSOR
    - OBJECT_SENSOR
    FORCE_TERMINATE:
        TYPE: ForceTerminate
        MAX_ACCUM_FORCE: 10_000.0
        MAX_INSTANT_FORCE: 10_000.0
    PLACE_REWARD:
        TYPE: PlaceReward
        DIST_REWARD: 2.0
        PLACE_REWARD: 5.0
        DROP_PEN: 0.0
        USE_DIFF: true
        MIN_DIST_TO_GOAL: 0.15
        USE_EE_DIST: False
        WRONG_DROP_SHOULD_END: True
        CONSTRAINT_VIOLATE_PEN: 0.0
        FORCE_PEN: 0.0001
        MAX_FORCE_PEN: 0.0
        FORCE_END_PEN: 1.0
    END_EFFECTOR_TO_GOAL_DISTANCE:
        TYPE: EndEffectorToGoalDistance
    MEASUREMENTS:
    - ROBOT_FORCE
    - FORCE_TERMINATE
    - ROBOT_COLLS
    - END_EFFECTOR_TO_GOAL_DISTANCE
    - END_EFFECTOR_TO_REST_DISTANCE
    - OBJECT_TO_GOAL_DISTANCE
    - OBJ_AT_GOAL
    - PLACE_SUCCESS
    - PLACE_REWARD
    - NUM_STEPS
    ACTIONS:
        ARM_ACTION:
            GRIP_CONTROLLER: SuctionGraspAction
            ARM_JOINT_DIMENSIONALITY: 7
    POSSIBLE_ACTIONS:
    - ARM_ACTION
    - BASE_VELOCITY
SIMULATOR:
    ADDITIONAL_OBJECT_PATHS:
    - data/objects/ycb/configs/
    DEBUG_RENDER: false
    DEBUG_RENDER_GOAL: true
    ACTION_SPACE_CONFIG: v0
    AGENTS:
    - AGENT_0
    NEEDS_MARKERS: false
    CONCUR_RENDER: True
    AUTO_SLEEP: True
    AGENT_0:
        HEIGHT: 1.5
        RADIUS: 0.3
        SENSORS:
        - HEAD_DEPTH_SENSOR
        ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_suction_v2.urdf
        ROBOT_TYPE: FetchSuctionRobot
        IK_ARM_URDF: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
    HEAD_DEPTH_SENSOR:
        WIDTH: 256
        HEIGHT: 256
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: true
    HABITAT_SIM_V0:
        ALLOW_SLIDING: false
        ENABLE_PHYSICS: true
        GPU_DEVICE_ID: 0
        GPU_GPU: false
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    TYPE: RearrangeSim-v0
    ARM_DEPTH_SENSOR:
        WIDTH: 128
        HEIGHT: 128
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: true
    HEAD_RGB_SENSOR:
        WIDTH: 256
        HEIGHT: 256
    ARM_RGB_SENSOR:
        HEIGHT: 128
        WIDTH: 128
