GYM:
    AUTO_NAME: "ReachState"
    OBS_KEYS: ['joint', 'relative_resting_position']
    ACTION_KEYS: ['ARM_ACTION']
    CLASS_NAME: "RearrangeRLEnv"
ENVIRONMENT:
    MAX_EPISODE_STEPS: 20
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/{split}/empty_1k_100.json.gz
    SCENES_DIR: "data/replica_cad/"
TASK:
    BASE_ANGLE_NOISE: 0.0
    BASE_NOISE: 0.0
    TYPE: RearrangeReachTask-v0
    RENDER_TARGET: True
    EE_SAMPLE_FACTOR: 0.2
    EE_EXCLUDE_REGION: 0.0

    REWARD_MEASURE: "rearrange_reach_reward"
    SUCCESS_MEASURE: "rearrange_reach_success"
    SUCCESS_REWARD: 10.0
    END_ON_SUCCESS: True

    DESIRED_RESTING_POSITION: [0.5, 0.0, 1.0]

    JOINT_SENSOR:
        TYPE: "JointSensor"
        DIMENSIONALITY: 7
    RELATIVE_RESTING_POS_SENSOR:
        TYPE: "RelativeRestingPositionSensor"
    RESTING_POS_SENSOR:
        TYPE: "RestingPositionSensor"
    END_EFFECTOR_SENSOR:
        TYPE: "EEPositionSensor"
    JOINT_VELOCITY_SENSOR:
        TYPE: "JointVelocitySensor"
        DIMENSIONALITY: 7
    SENSORS: ["JOINT_SENSOR", "JOINT_VELOCITY_SENSOR", "RELATIVE_RESTING_POS_SENSOR", 'END_EFFECTOR_SENSOR', "RESTING_POS_SENSOR"]

    END_EFFECTOR_TO_REST_DISTANCE:
        TYPE: "EndEffectorToRestDistance"
    REARRANGE_REACH_REWARD:
        TYPE: "RearrangeReachReward"
        SCALE: 1.0
        DIFF_REWARD: True
        SPARSE_REWARD: False
    REARRANGE_REACH_SUCCESS:
        TYPE: "RearrangeReachSuccess"
        SUCC_THRESH: 0.2
    NUM_STEPS:
        TYPE: "NumStepsMeasure"
    MEASUREMENTS:
        - "END_EFFECTOR_TO_REST_DISTANCE"
        - "REARRANGE_REACH_SUCCESS"
        - "REARRANGE_REACH_REWARD"
        - "NUM_STEPS"
    ACTIONS:
        ARM_ACTION:
            TYPE: "ArmAction"
            ARM_CONTROLLER: "ArmRelPosAction"
            ARM_JOINT_DIMENSIONALITY: 7
            GRIP_CONTROLLER: null
            GRASP_THRESH_DIST: 0.15
            SHOULD_CLIP: True
            DELTA_POS_LIMIT: 0.0125
            RENDER_EE_TARGET: True
            EE_CTRL_LIM: 0.015
    POSSIBLE_ACTIONS:
        - ARM_ACTION

SIMULATOR:
    ACTION_SPACE_CONFIG: v0
    AGENTS: ['AGENT_0']
    ROBOT_JOINT_START_NOISE: 0.0
    CONCUR_RENDER: True
    AUTO_SLEEP: True
    DEBUG_RENDER: False
    DEBUG_RENDER_GOAL: True
    AGENT_0:
        HEIGHT: 1.5
        IS_SET_START_STATE: True
        RADIUS: 0.3
        SENSORS: [HEAD_DEPTH_SENSOR]
        START_POSITION: [0.0, 0.0, 2.0]
        START_ROTATION: [0.0, 0.0, 0.0, 1.0]
    HEAD_DEPTH_SENSOR:
        WIDTH: 32
        HEIGHT: 32
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: True

    # Agent setup
    ARM_REST: [0.6, 0.0, 0.9]
    CTRL_FREQ: 120.0
    AC_FREQ_RATIO: 8
    ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_fetch.urdf
    ROBOT_TYPE: "FetchRobot"
    EE_LINK_NAME: null
    FORWARD_STEP_SIZE: 0.25
    LAG_OBSERVATIONS: 0
    LOAD_OBJS: False
    IK_ARM_URDF: null

    # Grasping
    HOLD_THRESH: 0.09
    GRASP_IMPULSE: 1000.0

    DEFAULT_AGENT_ID: 0
    HABITAT_SIM_V0:
        ALLOW_SLIDING: False
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    SEMANTIC_SENSOR:
        HEIGHT: 480
        HFOV: 90
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 1.25, 0]
        TYPE: HabitatSimSemanticSensor
        WIDTH: 640
    TILT_ANGLE: 15
    TURN_ANGLE: 10
    TYPE: RearrangeSim-v0
