# Config for empty task to explore the scene.
ENVIRONMENT:
    MAX_EPISODE_STEPS: 0
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/fremont/test.json.gz
    SCENES_DIR: "data/fremont/"
TASK:
    TYPE: RearrangeEmptyTask-v0
    COUNT_OBJ_COLLISIONS: True
    COUNT_ROBOT_OBJ_COLLS: False
    DESIRED_RESTING_POSITION: [0.5, 0.0, 1.0]

    # Reach task config
    RENDER_TARGET: True
    EE_SAMPLE_FACTOR: 0.8

    # In radians
    BASE_ANGLE_NOISE: 0.0
    BASE_NOISE: 0.0
    CONSTRAINT_VIOLATION_ENDS_EPISODE: False

    # If true, does not care about navigability or collisions with objects when spawning
    # robot
    EASY_INIT: False
    FORCE_REGENERATE: True

    SENSORS: ["JOINT_SENSOR"]

    MEASUREMENTS:
        # General measure
        - "ROBOT_FORCE"
    ACTIONS:
        ARM_ACTION:
            TYPE: "ArmAction"
            ARM_CONTROLLER: "ArmRelPosAction"
            GRIP_CONTROLLER: "MagicGraspAction"
            ARM_JOINT_DIMENSIONALITY: 7
            GRASP_THRESH_DIST: 0.15
            DISABLE_GRIP: False
            DELTA_POS_LIMIT: 0.0125
            EE_CTRL_LIM: 0.015
        BASE_VELOCITY:
            TYPE: "BaseVelAction"
            LIN_SPEED: 15.0
            ANG_SPEED: 15.0
            ALLOW_DYN_SLIDE: True
            END_ON_STOP: False
            ALLOW_BACK: True
            MIN_ABS_LIN_SPEED: 1.0
            MIN_ABS_ANG_SPEED: 1.0
        EMPTY:
            TYPE: "EmptyAction"
    POSSIBLE_ACTIONS:
        - ARM_ACTION
        - BASE_VELOCITY
        - EMPTY

SIMULATOR:
    ACTION_SPACE_CONFIG: v0
    GRASP_IMPULSE: 1000.0
    HOLD_THRESH: 0.09
    AC_FREQ_RATIO: 4
    DEBUG_RENDER: False
    DEBUG_RENDER_GOAL: True
    AGENTS: ['AGENT_0']
    AGENT_0:
        HEIGHT: 1.5
        RADIUS: 0.3
        SENSORS: ['HEAD_DEPTH_SENSOR']
        ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_fetch.urdf
        ROBOT_TYPE: "FetchRobot"
        IK_ARM_URDF: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
    HEAD_RGB_SENSOR:
        WIDTH: 128
        HEIGHT: 128
    HEAD_DEPTH_SENSOR:
        WIDTH: 128
        HEIGHT: 128
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: True
    ARM_REST: [0.6, 0.0, 0.9]
    CTRL_FREQ: 120.0
    DEFAULT_AGENT_ID: 0
    FORWARD_STEP_SIZE: 0.25
    HABITAT_SIM_V0:
        ALLOW_SLIDING: False
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    TYPE: RearrangeSim-v0
