habitat:
  simulator:
    agent_0:
      sensors: ["depth_sensor"]

habitat_baselines:
  trainer_name: "ppo"
  env_name: "NavRLEnv"
  simulator_gpu_id: 0
  torch_gpu_id: 0
  video_option: ["disk", "tensorboard"]
  tensorboard_dir: "tb"
  video_dir: "video_dir"
  test_episode_count: 2
  eval_ckpt_path_dir: "data/new_checkpoints"
  simulators_per_gpu: 2
  sensors: ["rgb_sensor", "depth_sensor"]
  checkpoint_folder: "data/new_checkpoints"
  num_updates: 10000
  log_interval: 10
  checkpoint_interval: 50

  rl:
    ppo:
      # ppo params
      clip_param: 0.1
      ppo_epoch: 2
      num_mini_batch: 1
      value_loss_coef: 0.5
      entropy_coef: 0.01
      lr: 2.5e-4
      eps: 1e-5
      max_grad_norm: 0.5
      num_steps: 128
      hidden_size: 512
      use_gae: True
      gamma: 0.99
      tau: 0.95
      use_linear_clip_decay: True
      use_linear_lr_decay: True
      reward_window_size: 50
