# @package _global_

defaults:
  - social_rearrange: pop_play
  - hitl_defaults
  - disable_spot_pick_and_move_backward
  - _self_

habitat:
  # various config args to ensure the episode never ends
  environment:
    max_episode_steps: 0
    iterator_options:
      # For the demo, we want to showcase the episodes in the specified order
      shuffle: False
  task:
    measurements:
      rearrange_cooperate_reward:
        end_on_collide: False
      pddl_success:
        must_call_stop: False
  dataset:
    data_path: examples/hitl/rearrange_v2/app_data/demo.json.gz



habitat_baselines:
  # todo: document these choices
  eval:
    should_load_ckpt: False
  rl:
    agent:
      num_pool_agents_per_type: [1,1]

habitat_hitl:
  window:
    title: "Rearrange"
    width: 1300
    height: 1000
  gui_controlled_agents:
    - agent_index: 1
      lin_speed: 10.0
      ang_speed: 300
  hide_humanoid_in_gui: True
  camera:
    first_person_mode: True
